-- Argos One — Phase 1: makes + models catalog
-- Paste this whole file into the Supabase SQL Editor and run it.

-- ── Tables ────────────────────────────────────────────────────────────────
create table if not exists makes (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  is_custom  boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists makes_name_lower_idx on makes (lower(name));

create table if not exists models (
  id         uuid primary key default gen_random_uuid(),
  make_id    uuid not null references makes(id) on delete cascade,
  name       text not null,
  is_custom  boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists models_make_name_lower_idx on models (make_id, lower(name));

-- ── Row-Level Security ────────────────────────────────────────────────────
-- The catalog is shared: anyone (incl. anon publishable key) can read and add.
alter table makes  enable row level security;
alter table models enable row level security;

create policy "catalog read makes"   on makes  for select using (true);
create policy "catalog add makes"    on makes  for insert with check (true);
create policy "catalog read models"  on models for select using (true);
create policy "catalog add models"   on models for insert with check (true);

-- Argos One — Phase 1 seed: makes + models
-- Run AFTER the table DDL. Safe to re-run (on conflict do nothing).

insert into makes (name) values
  ('Audi'),
  ('BMW'),
  ('Ford'),
  ('Holden'),
  ('Honda'),
  ('Hyundai'),
  ('Isuzu'),
  ('Jeep'),
  ('Kia'),
  ('Land Rover'),
  ('Lexus'),
  ('Mazda'),
  ('Mercedes-Benz'),
  ('MG'),
  ('Mitsubishi'),
  ('Nissan'),
  ('Subaru'),
  ('Suzuki'),
  ('Tesla'),
  ('Toyota'),
  ('Volkswagen'),
  ('Volvo')
on conflict do nothing;

insert into models (make_id, name)
select mk.id, x.model
from (values
  ('Audi','A1'),
  ('Audi','A3'),
  ('Audi','A4'),
  ('Audi','A5'),
  ('Audi','A6'),
  ('Audi','Q2'),
  ('Audi','Q3'),
  ('Audi','Q5'),
  ('Audi','Q7'),
  ('Audi','Q8'),
  ('Audi','S3'),
  ('Audi','SQ5'),
  ('Audi','RS3'),
  ('Audi','e-tron'),
  ('BMW','1 Series'),
  ('BMW','2 Series'),
  ('BMW','3 Series'),
  ('BMW','4 Series'),
  ('BMW','5 Series'),
  ('BMW','X1'),
  ('BMW','X3'),
  ('BMW','X5'),
  ('BMW','M3'),
  ('BMW','M5'),
  ('Ford','Ranger'),
  ('Ford','Everest'),
  ('Ford','Escape'),
  ('Ford','Focus'),
  ('Ford','Falcon'),
  ('Ford','Territory'),
  ('Ford','Mustang'),
  ('Ford','Transit'),
  ('Holden','Commodore'),
  ('Holden','Colorado'),
  ('Holden','Astra'),
  ('Holden','Barina'),
  ('Holden','Captiva'),
  ('Holden','Cruze'),
  ('Holden','Trax'),
  ('Honda','Accord'),
  ('Honda','City'),
  ('Honda','Civic'),
  ('Honda','CR-V'),
  ('Honda','HR-V'),
  ('Honda','Jazz'),
  ('Honda','Odyssey'),
  ('Hyundai','i20'),
  ('Hyundai','i30'),
  ('Hyundai','Accent'),
  ('Hyundai','Elantra'),
  ('Hyundai','Kona'),
  ('Hyundai','Santa Fe'),
  ('Hyundai','Tucson'),
  ('Hyundai','iLoad'),
  ('Isuzu','D-Max'),
  ('Isuzu','MU-X'),
  ('Jeep','Cherokee'),
  ('Jeep','Grand Cherokee'),
  ('Jeep','Wrangler'),
  ('Jeep','Compass'),
  ('Kia','Cerato'),
  ('Kia','Picanto'),
  ('Kia','Rio'),
  ('Kia','Seltos'),
  ('Kia','Sorento'),
  ('Kia','Sportage'),
  ('Kia','Carnival'),
  ('Land Rover','Defender'),
  ('Land Rover','Discovery'),
  ('Land Rover','Range Rover'),
  ('Land Rover','Range Rover Evoque'),
  ('Land Rover','Range Rover Sport'),
  ('Lexus','CT'),
  ('Lexus','ES'),
  ('Lexus','IS'),
  ('Lexus','NX'),
  ('Lexus','RX'),
  ('Lexus','UX'),
  ('Mazda','Mazda2'),
  ('Mazda','Mazda3'),
  ('Mazda','Mazda6'),
  ('Mazda','CX-3'),
  ('Mazda','CX-30'),
  ('Mazda','CX-5'),
  ('Mazda','CX-8'),
  ('Mazda','CX-9'),
  ('Mazda','BT-50'),
  ('Mazda','MX-5'),
  ('Mercedes-Benz','A-Class'),
  ('Mercedes-Benz','C-Class'),
  ('Mercedes-Benz','E-Class'),
  ('Mercedes-Benz','GLA'),
  ('Mercedes-Benz','GLC'),
  ('Mercedes-Benz','GLE'),
  ('Mercedes-Benz','Sprinter'),
  ('Mercedes-Benz','Vito'),
  ('MG','MG3'),
  ('MG','ZS'),
  ('MG','HS'),
  ('MG','MG5'),
  ('Mitsubishi','ASX'),
  ('Mitsubishi','Eclipse Cross'),
  ('Mitsubishi','Outlander'),
  ('Mitsubishi','Pajero'),
  ('Mitsubishi','Pajero Sport'),
  ('Mitsubishi','Triton'),
  ('Nissan','Navara'),
  ('Nissan','Qashqai'),
  ('Nissan','X-Trail'),
  ('Nissan','Patrol'),
  ('Nissan','Pathfinder'),
  ('Nissan','Juke'),
  ('Nissan','Leaf'),
  ('Subaru','Impreza'),
  ('Subaru','WRX'),
  ('Subaru','Forester'),
  ('Subaru','Outback'),
  ('Subaru','XV'),
  ('Subaru','Liberty'),
  ('Subaru','BRZ'),
  ('Suzuki','Swift'),
  ('Suzuki','Baleno'),
  ('Suzuki','Vitara'),
  ('Suzuki','Jimny'),
  ('Suzuki','Ignis'),
  ('Suzuki','S-Cross'),
  ('Tesla','Model 3'),
  ('Tesla','Model Y'),
  ('Tesla','Model S'),
  ('Tesla','Model X'),
  ('Toyota','Corolla'),
  ('Toyota','Camry'),
  ('Toyota','RAV4'),
  ('Toyota','HiLux'),
  ('Toyota','LandCruiser'),
  ('Toyota','Prado'),
  ('Toyota','Kluger'),
  ('Toyota','Yaris'),
  ('Toyota','C-HR'),
  ('Toyota','Fortuner'),
  ('Volkswagen','Golf'),
  ('Volkswagen','Polo'),
  ('Volkswagen','Tiguan'),
  ('Volkswagen','T-Cross'),
  ('Volkswagen','T-Roc'),
  ('Volkswagen','Amarok'),
  ('Volkswagen','Passat'),
  ('Volkswagen','Touareg'),
  ('Volvo','XC40'),
  ('Volvo','XC60'),
  ('Volvo','XC90'),
  ('Volvo','S60'),
  ('Volvo','V60')
) as x(make, model)
join makes mk on lower(mk.name) = lower(x.make)
on conflict do nothing;
